### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ldmatev** [scala-network/XLArig#19]
Hi,
I receive this error.
Could you help me? Thanks
$ ./xlarig
WARNING: linker: ./xlarig: unused DT entry: type 0x6ffffef5 arg 0xc08
 * ABOUT        XLArig/5.1.0 clang/9.0.0
 * LIBS         libuv/1.33.1 OpenSSL/1.1.1d
 * HUGE PAGES   supported
 * 1GB PAGES    unavailable
 * CPU          ARMv7 (1) -x64 -AES
                threads:4
 * MEMORY       1.6/1.9 GB (80%)
 * DONATE       1%
 * POOL #1      xmr-eu1.nanopool.org:14433 algo rx/0
 * COMMANDS     hashrate, pause, resume
Segmentation fault

**Comment by ldmatev** [comment]
Hi, 
Any news?
Thanks in advance

**Comment by woodycal** [comment]
> Hi,
> I receive this error.
> Could you help me? Thanks
> $ ./xlarig
> WARNING: linker: ./xlarig: unused DT entry: type 0x6ffffef5 arg 0xc08
> 
> * ABOUT        XLArig/5.1.0 clang/9.0.0
> * LIBS         libuv/1.33.1 OpenSSL/1.1.1d
> * HUGE PAGES   supported
> * 1GB PAGES    unavailable
> * CPU          ARMv7 (1) -x64 -AES
>   threads:4
> * MEMORY       1.6/1.9 GB (80%)
> * DONATE       1%
> * POOL #1      xmr-eu1.nanopool.org:14433 algo rx/0
> * COMMANDS     hashrate, pause, resume
>   Segmentation fault

Did you build this from source? Also what os you using.

**Comment by jafloresmartin** [comment]
same problem, any idea?

**Comment by Teredic** [comment]
You must be in a 64 bit container shell to be able to mine with your raspberry.

First you need to install the package :
``sudo apt-get install -y raspbian-nspawn-64``

Then you start it : ``ds64-shell``

Since it's an independant instance, you should do the usual (sudo apt update/upgrade) as if it were a new system.

Then you download the miner (or compile), put your settings and start xlarig.
